<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CmScheme.Dashboard.Core\CmScheme.Dashboard.Core.csproj" />
    <ProjectReference Include="..\CmScheme.Common.Core\CmScheme.Common.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
  </ItemGroup>
</Project>
