<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CmScheme.Dashboard.Core\CmScheme.Dashboard.Core.csproj" />
    <ProjectReference Include="..\CmScheme.Common.Core\CmScheme.Common.Core.csproj" />
    <ProjectReference Include="..\CmScheme.Registration.Core\CmScheme.Registration.Core.csproj" />
    <ProjectReference Include="..\CmScheme.Training.Core\CmScheme.Training.Core.csproj" />
    <ProjectReference Include="..\CmScheme.WorkAllocation.Core\CmScheme.WorkAllocation.Core.csproj" />
    <ProjectReference Include="..\CmScheme.AttendanceLeave.Core\CmScheme.AttendanceLeave.Core.csproj" />
    <ProjectReference Include="..\CmScheme.Performance.Core\CmScheme.Performance.Core.csproj" />
    <ProjectReference Include="..\CmScheme.HelpDesk.Core\CmScheme.HelpDesk.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Scrutor" Version="4.2.2" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="QuestPDF" Version="2024.12.1" />
    <PackageReference Include="EPPlus" Version="7.0.0" />
  </ItemGroup>
</Project>
