<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CmScheme.Registration.Core\CmScheme.Registration.Core.csproj" />
    <ProjectReference Include="..\CmScheme.Registration.Application\CmScheme.Registration.Application.csproj" />
    <ProjectReference Include="..\CmScheme.Endpoints.Abstractions\CmScheme.Endpoints.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="Scrutor" Version="4.2.2" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Ardalis.Result.FluentValidation" Version="10.1.0" />
  </ItemGroup>

</Project>
